# Generated by Django 3.1 on 2020-08-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_ts',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_ts',
            field=models.DateField(null=True),
        ),
    ]
