# Generated by Django 3.1 on 2020-08-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200825_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featuredImage',
            field=models.ImageField(height_field=300, upload_to='blog/image', width_field=400),
        ),
    ]
