# Generated by Django 3.1 on 2020-08-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200828_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=100)),
                ('site_description', models.TextField()),
                ('meta_tags', models.CharField(max_length=500)),
                ('created_ts', models.DateField()),
                ('updated_ts', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='featuredImage',
            field=models.ImageField(upload_to='blog/image'),
        ),
    ]
